[google_cloud]
type = "service_account"
project_id = "lithe-willow-462605-g8"
private_key_id = "5707753cafc8970b0c6e2fbc33abb18dd1d0329f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrdFQesu6IcS6T
jktZtAyvSd4eh+0vUwzRo6uY9ERLVJuhlMubrmCFu98TsThf1XXKghzR5muoA8Md
AFgqxS1le8lkCEYxXqxGCJKlF4aVCT+8OwTuMe5Jd+Q8tAL04z/np2UiXT9ifIFe
BYufK/jDJhmcyeVUxkOWrJMNwrjhE+AB7/bt+l89mIJP0M6dnq+3U69YUhhF0zEM
Cp4dLPP2pOi9RqkklKkkyzFXfcRFkhsXCWO6XhIqAhE/MrLTGBBaOt7Q4yJEFn7Q
KSC9nuTSYfuc+gtIukY4r30JUlvIeDmSBNOjNqHu+6RH/qt9U8XT9C7U5RyeuS10
bNa+KuHHAgMBAAECggEAOksA1rcrVoR0u4JjqAoJTgelV2gLgk2QTC6Dhyt1lM8d
YuB+IV42PwHTJJTaf+rJc6KtPchDzgoJanDViSUk/B4MKNCPXPW9SMpdYXgQL9fH
La47TOj5BU2X8fOaFby124MUZYyiok+GhHsKL4H5wA/SIXabXClUjYP7M3CC/zL9
J+eml5JI/XPSaKpfyKUPtpx0SaoY34ZVXlZvhoDdqJsP86pTmSlU/PQK4CQQU+OU
w2ddOQsjx4uYnVT6qIeuZgo3GpEz7vZro6d7arc0Jx7nKPD7Dk+ZQsAmV7h/+MA0
VvIk6nsYnP7Rl8q89/Gf3kzphUc4RJS9DhOecQTygQKBgQDtCLp39+vhaysMXPLT
qC0qhN0ZbmdT0cZSw/HHC1LAik6vCqgrhmYrx4KhA2McYOa+37TCHJ0zmW4ibcvO
SHtAFTyXSfedho8E6hrIZ76oOCkfbk/m1+IzODcYDijPywUu8UhK+MLqV/n4KaId
eaLGrFL8XLwx7A4peKiEfykSJwKBgQC5LE2eCV8GCinQheskQwf0UsqnB/fV95BF
MXc8cE+p291ajFWQ/pB9bhd2G7pTbQvE6preUeXyXTSvu3B/a4rJuVMlzx0rK2JE
fxnSZLCR6q36CGGfiwgagv5AuRcfMml+N8odlI29Jkg1aAC5pGTfQw6BpmgLB9BK
VVP/eKqXYQKBgQDQQzEDI3O/FZg3PpukWEmG6EITjCuBO/lS0xLl3g8RWPQVW/my
dF3k7WDa88zrLEDRSGDbhKSip5Za7bl6P7j67y3Th4vmfkm++aoalvyvdNi84wGV
Q+1dL3FI03gMSsb9HcZ1COjJWg8pefsUhsD8aoBnd1trSYqP6ZG3CLsfVQKBgEU8
Q2krp9PiSPAmolzUk0zPB+acHBZskgzNCgAXHjIsev84KWYlSHEdkLggdfJre1MN
RQqLJKcSInjyZIW/+AyktmoUnptdhUiHHWiFLV/hl1s9dwLoQQdooxggHH0VpEwF
IBUfTj/C6IzPbjX7OZwgvnPLfGtjaIXikZ2byG0BAoGAWk5t1gWwIO4dRZy6tqbd
ikLMZe1gLl0a2L/AywXYPLIfC5/7stgqr+qc4Xeu6tiPZZ91cKWW6avo/YyNAqAi
IohrTlPZ6xqOE5l0j7hj4OGfM5kaOA9Y+AsuCTvrJCcn9IClWWzMprZBtKR+6PmT
AvDnCHFbpW8XeN46TgKZZX0=
-----END PRIVATE KEY-----"""
client_email = "hiss-967@lithe-willow-462605-g8.iam.gserviceaccount.com"
client_id = "112342286816233062980"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hiss-967%40lithe-willow-462605-g8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
