[google_cloud]
type = "service_account"
project_id = "lithe-willow-462605-g8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrdFQesu6IcS6T
jktZtAyvSd4eh+0vUwzRo6uY9ERLVJuhlMubrmCFu98TsThf1XXKghzR5muoA8Md
...중략...
-----END PRIVATE KEY-----"""
client_email = "hiss-967@lithe-willow-462605-g8.iam.gserviceaccount.com"
client_id = "112342286816233062980"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hiss-967%40lithe-willow-462605-g8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
